[package]
name = "test_serial"
version = "0.1.0"
authors = ["Nate Fatkhiyev <nfatkhiyev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport ="3.3.0"
